### ISSUE TITLE
Script to compile protos?

### ISSUE THREAD

**Issue by remingtonc** [ios-xr/model-driven-telemetry#1]
Is there a `protoc` script used to compile the protos to Go for easier usage/deserialization? Any documentation would be extremely useful.

The bigmuddy repo had this [prep_golang.py](https://github.com/cisco/bigmuddy-network-telemetry-proto/blob/master/prep_golang.py) script which seems relevant.

In general this would be useful and could be used as a template for adapting other `protoc` plugins if requests for other languages happen.

**Comment by Jhors2** [comment]
prep_golang.py should accomplish what is necessary, it would be ncie as a part of updating this repo if that script was run and the changes were pushed into the repo.  This will make dependency management for golang projects a lot simpler rather than having to fork the repo or run the script as a part of the build process.

**Comment by adithyasesani** [comment]
A slightly modified prep_golang.py script is available at https://github.com/ios-xr/telemetry-proto-go-plugins. I will add that as sub-module to this repo. This script will allow generating just "go" bindings for the protos.

The one available in bigmuddy is still relevant for generating bindings as well as wrapper code needed for rebuilding pipeline with new protos.

**Comment by remingtonc** [comment]
Alternative adaptation also in https://github.com/cisco-ie/cisco-proto/tree/master/scripts/codegen/xr/go
Vendorable Go code at https://github.com/cisco-ie/cisco-proto/tree/master/codegen/go
